[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "soon-bin"
requires-python = ">=3.10"
description = "Local-first prediction for your next full shell command"
readme = "README.md"
license = "MIT"
authors = [
    { name = "HsiangNianian", email = "i@jyunko.cn" }
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "rich>=14.0.0",
]

[project.urls]
Homepage = "https://soon.hydroroll.team"
Repository = "https://github.com/HsiangNianian/soon"
Issues = "https://github.com/HsiangNianian/soon/issues"

[tool.maturin]
bindings = "bin"
module-name = "soon"
